version: '3.8'

services:
  rnabridge:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./cif:/app/cif
      - ./x3dna-v2.4:/app/x3dna-v2.4
      - ./rnabridge.db:/app/rnabridge.db
    environment:
      - X3DNA=/app/x3dna-v2.4
      - DATABASE_URL=sqlite:///app/rnabridge.db
    restart: always
